version: '2'

services:
  api:
    container_name: 'api-run'
    build: './api'
    ports:
      - '3030:3030'
    expose:
      - '27017'
    volumes:
      - './api:/go/src/github.com/GeoServer/project/api'
    environment:
      - DB_NAME=project
    depends_on:
      - 'mongo'
    links:
      - mongo:mongo
    networks:
      - dbnetwork
      - webnetwork

  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - dbnetwork

  nginx:
    build: "./nginx"
    ports:
      - "8020:8020"
      - "8080:8080"
    depends_on:
      - "api"
    networks:
      - webnetwork

networks:
  dbnetwork:
  webnetwork:
